/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Unidad_11;

import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author hckr
 */
public class MarcoRadioButton extends javax.swing.JFrame {

    private final Font simple;
    private final Font bold;
    private final Font italic;
    private final Font boldItalic;
    
    /**
     * Creates new form MarcoRadioButton
     */
    public MarcoRadioButton() {
        initComponents();
        simple = new Font("Serif", Font.PLAIN, 14);
        bold = new Font("Serif", Font.BOLD, 14);
        italic = new Font("Serif", Font.ITALIC, 14);
        boldItalic = new Font("Serif", Font.BOLD + Font.ITALIC, 14);
        
        rbGroupText.add(rbSimple);
        rbGroupText.add(rbBold);
        rbGroupText.add(rbItalic);
        rbGroupText.add(rbBoldItalic);
        
        rbSimple.addItemListener(
        new ManejadorRadioButton(simple)
        );
        rbBold.addItemListener(
        new ManejadorRadioButton(bold)
        );
        rbItalic.addItemListener(
        new ManejadorRadioButton(italic)
        );
        rbBoldItalic.addItemListener(
        new ManejadorRadioButton(boldItalic)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupText = new javax.swing.ButtonGroup();
        txtField = new javax.swing.JTextField();
        rbSimple = new javax.swing.JRadioButton();
        rbBold = new javax.swing.JRadioButton();
        rbItalic = new javax.swing.JRadioButton();
        rbBoldItalic = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtField.setText("Observer como cambia el estilo de tipo de letra");

        rbSimple.setText("Simple");

        rbBold.setText("Bold");

        rbItalic.setText("Italic");

        rbBoldItalic.setText("Bold/Italic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbSimple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbBold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbItalic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbBoldItalic)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSimple)
                    .addComponent(rbBold)
                    .addComponent(rbItalic)
                    .addComponent(rbBoldItalic))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MarcoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MarcoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MarcoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MarcoRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MarcoRadioButton().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton rbBold;
    private javax.swing.JRadioButton rbBoldItalic;
    private javax.swing.ButtonGroup rbGroupText;
    private javax.swing.JRadioButton rbItalic;
    private javax.swing.JRadioButton rbSimple;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables

    private class ManejadorRadioButton implements ItemListener{
        private final Font font;
        
        public ManejadorRadioButton(Font font){
            this.font = font;
        }
        
        @Override
        public void itemStateChanged(ItemEvent evento) {
            txtField.setFont(font);
        }
        
    }
}
